services:
  ai-coin-oracle:
    build: .
    container_name: ai-coin-oracle
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_EMAIL=${TWITTER_EMAIL}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - TZ=UTC
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "api.twitter.com:104.244.42.66"
      - "twitter.com:104.244.42.193"
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/src/__pycache__
      - /app/src/services/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3